[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo='Shougo/unite.vim'
hook_add="""
    set runtimepath^=~/.vim/dein/repos/github.com/Shougo/unite.vim
"""

[[plugins]]
repo='Shougo/neomru.vim'
hook_add="""
    set runtimepath^=~/.vim/dein/repos/github.com/Shougo/neomru.vim
"""

[[plugins]]
repo='Shougo/vimproc.vim'
hook_add="""
    set runtimepath^=~/.vim/dein/repos/github.com/Shougo/vimproc.vim
"""
hook_post_update="""
    let g:dein#plugin.build='make'
"""

[[plugins]]
repo='Shougo/neocomplete.vim'
hook_add="""
    if (has('lua') && (v:version > 703 || v:version == 703 && has('patch885')))
        set runtimepath^=~/.vim/dein/repos/github.com/Shougo/neocomplete.vim
        let g:acp_enableAtStartup = 0 " Disable AutoComplPop.
        let g:neocomplete#enable_at_startup = 1 " Use neocomplete.
        let g:neocomplete#enable_smart_case = 1 " Use smartcase.
        let g:neocomplete#sources#syntax#min_keyword_length = 3
        let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'
        inoremap <expr><C-g> neocomplete#undo_completion()
        inoremap <expr><C-l> neocomplete#complete_common_string()
        inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
        function! s:my_cr_function()
        return pumvisible() ? neocomplete#close_popup() : "\<CR>"
        endfunction
        inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
        inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
        inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
        inoremap <expr><C-y> neocomplete#close_popup()
        inoremap <expr><C-e> neocomplete#cancel_popup()
        inoremap <expr><Space> pumvisible() ?
            \ neocomplete#close_popup() . "\<Space>" : "\<Space>"
  endif
"""

